#!/usr/bin/env node

const max = process.argv[2]
console.log(random(max))

function random(max = 10) {
  const randomNr = Math.random() * (Number(max) + 1)
  const rounded = Math.floor(randomNr)
  return rounded
}
